//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtl_MIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtl_Partner
    {
        public string PartnerID { get; set; }
        public string Description { get; set; }
    }
}
