//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtl_MIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSLog
    {
        public int rid { get; set; }
        public string Partner { get; set; }
        public string IPaddress { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public string WSName { get; set; }
        public string WSMethod { get; set; }
        public string Detail { get; set; }
        public string RefRow { get; set; }
    }
}
